import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import LayoutWrapper from './_wrappers/mainWrapper'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  // TODO: Update
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <LayoutWrapper>
      <html lang='en'>
        <body className={inter.className}>{children}</body>
      </html>
    </LayoutWrapper>
  )
}
